# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 18:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('sale_cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('instructor', models.CharField(blank=True, max_length=120, null=True)),
                ('interval', models.CharField(max_length=50)),
                ('feature1', models.CharField(blank=True, max_length=120, null=True)),
                ('feature2', models.CharField(blank=True, max_length=120, null=True)),
                ('feature3', models.CharField(blank=True, max_length=120, null=True)),
                ('feature4', models.CharField(blank=True, max_length=120, null=True)),
                ('feature5', models.CharField(blank=True, max_length=120, null=True)),
                ('feature6', models.CharField(blank=True, max_length=120, null=True)),
                ('checkout_instructions', models.TextField(blank=True, null=True)),
                ('button_text', models.CharField(max_length=50)),
                ('classes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='classes.Classes')),
            ],
        ),
    ]
