# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-30 13:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20171130_1326'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='interval',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
