# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-30 14:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_interval'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='instructor',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
    ]
