# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-30 16:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_instructor'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='checkout_instructions',
            field=models.TextField(blank=True, null=True),
        ),
    ]
