# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-29 21:19
from __future__ import unicode_literals

import classes.models
from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Classes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField(blank=True, null=True)),
                ('image', stdimage.models.StdImageField(blank=True, upload_to=classes.models.download_media_location)),
            ],
        ),
    ]
