# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-11-29 23:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='classes',
            name='location',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='classes',
            name='venue',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
